const quiz = [ /* questions 5e */ 

{ question: "baby", choix: ["bébé", "adulte", "parent"], bonneReponse: 0 },
{ question: "birth", choix: ["naissance", "mort", "fête"], bonneReponse: 0 },
{ question: "wedding", choix: ["mariage", "anniversaire", "soirée"], bonneReponse: 0 },
{ question: "to spend time", choix: ["passer du temps", "perdre du temps", "gagner du temps"], bonneReponse: 0 },
{ question: "to visit", choix: ["rendre visite", "quitter", "attendre"], bonneReponse: 0 },
{ question: "to gather", choix: ["se rassembler", "partir", "courir"], bonneReponse: 0 },
{ question: "to stay", choix: ["rester", "partir", "sortir"], bonneReponse: 0 },
{ question: "to hear from", choix: ["avoir des nouvelles", "oublier", "ignorer"], bonneReponse: 0 },
{ question: "to take care of", choix: ["s’occuper de", "laisser", "casser"], bonneReponse: 0 },

{ question: "European", choix: ["européen", "africain", "américain"], bonneReponse: 0 },
{ question: "Asian", choix: ["asiatique", "européen", "océanien"], bonneReponse: 0 },
{ question: "New Zealander", choix: ["néo-zélandais", "canadien", "italien"], bonneReponse: 0 },
{ question: "Nigerian", choix: ["nigérian", "marocain", "espagnol"], bonneReponse: 0 },
{ question: "Kenyan", choix: ["kényan", "français", "anglais"], bonneReponse: 0 },
{ question: "Californian", choix: ["californien", "texan", "new-yorkais"], bonneReponse: 0 },

{ question: "curly", choix: ["bouclé", "raide", "lisse"], bonneReponse: 0 },
{ question: "wavy", choix: ["ondulé", "bouclé", "chauve"], bonneReponse: 0 },
{ question: "straight", choix: ["raide", "ondulé", "bouclé"], bonneReponse: 0 },
{ question: "bald", choix: ["chauve", "barbu", "grand"], bonneReponse: 0 },

{ question: "freckles", choix: ["taches de rousseur", "rides", "boutons"], bonneReponse: 0 },
{ question: "shy", choix: ["timide", "bruyant", "méchant"], bonneReponse: 0 },
{ question: "outgoing", choix: ["sociable", "timide", "fermé"], bonneReponse: 0 },
{ question: "friendly", choix: ["gentil", "méchant", "froid"], bonneReponse: 0 },
{ question: "selfish", choix: ["égoïste", "généreux", "gentil"], bonneReponse: 0 },
{ question: "clumsy", choix: ["maladroit", "rapide", "fort"], bonneReponse: 0 },
{ question: "good-looking", choix: ["beau", "laid", "vieux"], bonneReponse: 0 },
{ question: "fashionable", choix: ["à la mode", "vieux", "moche"], bonneReponse: 0 },

{ question: "pants", choix: ["pantalon", "chemise", "chaussures"], bonneReponse: 0 },
{ question: "boots", choix: ["bottes", "sandales", "chaussettes"], bonneReponse: 0 },
{ question: "sneakers", choix: ["baskets", "talons", "chaussons"], bonneReponse: 0 },
{ question: "trainers", choix: ["baskets", "bottes", "sandales"], bonneReponse: 0 },
{ question: "dungarees", choix: ["salopette", "robe", "manteau"], bonneReponse: 0 },

{ question: "tooth/teeth", choix: ["dent/dents", "main", "pied"], bonneReponse: 0 },
{ question: "cheeks", choix: ["joues", "bras", "jambes"], bonneReponse: 0 },
{ question: "tongue", choix: ["langue", "nez", "œil"], bonneReponse: 0 },
{ question: "knees", choix: ["genoux", "coudes", "épaules"], bonneReponse: 0 },
{ question: "ankles", choix: ["chevilles", "poignets", "doigts"], bonneReponse: 0 },
{ question: "wrist", choix: ["poignet", "coude", "épaule"], bonneReponse: 0 },
{ question: "toes", choix: ["orteils", "doigts", "talons"], bonneReponse: 0 },
{ question: "shoulder", choix: ["épaule", "dos", "tête"], bonneReponse: 0 },
{ question: "stomach", choix: ["ventre", "dos", "tête"], bonneReponse: 0 },
{ question: "lips", choix: ["lèvres", "dents", "joues"], bonneReponse: 0 },

{ question: "a baker", choix: ["boulanger", "boucher", "cuisinier"], bonneReponse: 0 },
{ question: "a mechanic", choix: ["mécanicien", "prof", "médecin"], bonneReponse: 0 },
{ question: "a chemist", choix: ["pharmacien", "boulanger", "chauffeur"], bonneReponse: 0 },
{ question: "a cook", choix: ["cuisinier", "serveur", "client"], bonneReponse: 0 },
{ question: "a writer", choix: ["écrivain", "lecteur", "acteur"], bonneReponse: 0 },
{ question: "a plumber", choix: ["plombier", "électricien", "peintre"], bonneReponse: 0 },
{ question: "a banker", choix: ["banquier", "vendeur", "chauffeur"], bonneReponse: 0 },
{ question: "a CEO", choix: ["directeur", "employé", "élève"], bonneReponse: 0 },
{ question: "a butcher", choix: ["boucher", "boulanger", "serveur"], bonneReponse: 0 },

{ question: "fox", choix: ["renard", "chien", "chat"], bonneReponse: 0 },
{ question: "owl", choix: ["hibou", "aigle", "corbeau"], bonneReponse: 0 },
{ question: "snake", choix: ["serpent", "araignée", "ver"], bonneReponse: 0 },
{ question: "lion", choix: ["lion", "tigre", "zèbre"], bonneReponse: 0 },
{ question: "zebra", choix: ["zèbre", "cheval", "âne"], bonneReponse: 0 },
{ question: "hawk", choix: ["faucon", "pigeon", "canard"], bonneReponse: 0 },
{ question: "spider", choix: ["araignée", "insecte", "mouche"], bonneReponse: 0 },
{ question: "buffalo", choix: ["buffle", "vache", "cheval"], bonneReponse: 0 },
{ question: "reindeer", choix: ["renne", "cerf", "cheval"], bonneReponse: 0 },
{ question: "kiwi", choix: ["kiwi (oiseau)", "pomme", "poire"], bonneReponse: 0 },
{ question: "leopard", choix: ["léopard", "tigre", "lion"], bonneReponse: 0 },
{ question: "tiger", choix: ["tigre", "lion", "chat"], bonneReponse: 0 }

{ question: "to wash one's hands", choix: ["se laver les mains", "se brosser les dents", "se coucher"], bonneReponse: 0 },
{ question: "to brush one's teeth", choix: ["se brosser les dents", "se laver", "manger"], bonneReponse: 0 },
{ question: "to tidy", choix: ["ranger", "salir", "casser"], bonneReponse: 0 },
{ question: "to help at home", choix: ["aider à la maison", "jouer", "sortir"], bonneReponse: 0 },
{ question: "to go shopping", choix: ["faire les courses", "travailler", "dormir"], bonneReponse: 0 },
{ question: "to visit friends/family", choix: ["rendre visite", "ignorer", "quitter"], bonneReponse: 0 },
{ question: "to walk the dog", choix: ["promener le chien", "nourrir le chat", "courir"], bonneReponse: 0 },
{ question: "to relax", choix: ["se détendre", "travailler", "courir"], bonneReponse: 0 },
{ question: "to read", choix: ["lire", "écrire", "parler"], bonneReponse: 0 },
{ question: "to listen to music", choix: ["écouter de la musique", "chanter", "danser"], bonneReponse: 0 },
{ question: "to chat on social media", choix: ["discuter sur les réseaux", "étudier", "courir"], bonneReponse: 0 },

{ question: "semi-detached house", choix: ["maison jumelée", "appartement", "château"], bonneReponse: 0 },
{ question: "neighbourhood", choix: ["quartier", "ville", "pays"], bonneReponse: 0 },
{ question: "the house next door", choix: ["maison d’à côté", "école", "magasin"], bonneReponse: 0 },
{ question: "to decorate", choix: ["décorer", "casser", "nettoyer"], bonneReponse: 0 },
{ question: "to paint", choix: ["peindre", "dessiner", "effacer"], bonneReponse: 0 },
{ question: "cosy", choix: ["confortable", "froid", "vide"], bonneReponse: 0 },

{ question: "the rules", choix: ["les règles", "les jeux", "les devoirs"], bonneReponse: 0 },
{ question: "pawn", choix: ["pion", "roi", "tour"], bonneReponse: 0 },
{ question: "fair play", choix: ["esprit sportif", "triche", "mensonge"], bonneReponse: 0 },

{ question: "lunch box", choix: ["boîte à déjeuner", "sac", "assiette"], bonneReponse: 0 },
{ question: "dinner time", choix: ["heure du dîner", "matin", "récréation"], bonneReponse: 0 },
{ question: "packed lunch", choix: ["repas à emporter", "restaurant", "petit-déjeuner"], bonneReponse: 0 },
{ question: "baked beans", choix: ["haricots à la sauce tomate", "riz", "pâtes"], bonneReponse: 0 },
{ question: "spare ribs", choix: ["côtes de porc", "poulet", "poisson"], bonneReponse: 0 },
{ question: "maple taffy", choix: ["bonbon à l’érable", "chocolat", "gâteau"], bonneReponse: 0 },

{ question: "sports hall", choix: ["gymnase", "classe", "bibliothèque"], bonneReponse: 0 },
{ question: "aqua park", choix: ["parc aquatique", "zoo", "musée"], bonneReponse: 0 },
{ question: "water sports", choix: ["sports nautiques", "football", "tennis"], bonneReponse: 0 },
{ question: "to have fun", choix: ["s’amuser", "travailler", "dormir"], bonneReponse: 0 },
{ question: "to enjoy", choix: ["aimer", "détester", "ignorer"], bonneReponse: 0 },
{ question: "to see friends", choix: ["voir ses amis", "étudier", "voyager"], bonneReponse: 0 },

{ question: "collecting", choix: ["collectionner", "jeter", "acheter"], bonneReponse: 0 },
{ question: "acting", choix: ["jouer (théâtre)", "chanter", "dessiner"], bonneReponse: 0 },
{ question: "during my free time", choix: ["pendant mon temps libre", "à l’école", "au travail"], bonneReponse: 0 },
{ question: "once a week", choix: ["une fois par semaine", "tous les jours", "jamais"], bonneReponse: 0 },

{ question: "tradition", choix: ["tradition", "nouveauté", "erreur"], bonneReponse: 0 },
{ question: "celebration", choix: ["célébration", "travail", "cours"], bonneReponse: 0 },
{ question: "Easter eggs", choix: ["œufs de Pâques", "bonbons", "gâteaux"], bonneReponse: 0 },
{ question: "Bank Holiday", choix: ["jour férié", "jour d’école", "week-end"], bonneReponse: 0 },
{ question: "Independence Day", choix: ["fête nationale", "Noël", "Pâques"], bonneReponse: 0 },
{ question: "Diwali", choix: ["fête des lumières", "fête du sport", "fête de l’école"], bonneReponse: 0 },

{ question: "flower", choix: ["fleur", "arbre", "herbe"], bonneReponse: 0 },
{ question: "plant", choix: ["plante", "rocher", "eau"], bonneReponse: 0 },
{ question: "nature", choix: ["nature", "ville", "route"], bonneReponse: 0 },
{ question: "field", choix: ["champ", "forêt", "mer"], bonneReponse: 0 },
{ question: "meadow", choix: ["prairie", "montagne", "lac"], bonneReponse: 0 },
{ question: "cliff", choix: ["falaise", "colline", "plaine"], bonneReponse: 0 },
{ question: "canyon", choix: ["canyon", "rivière", "forêt"], bonneReponse: 0 },
{ question: "valley", choix: ["vallée", "montagne", "désert"], bonneReponse: 0 },
{ question: "rock", choix: ["rocher", "sable", "eau"], bonneReponse: 0 },
{ question: "bush", choix: ["buisson", "arbre", "fleur"], bonneReponse: 0 }

{ question: "once upon a time", choix: ["il était une fois", "maintenant", "demain"], bonneReponse: 0 },
{ question: "so far so good", choix: ["jusqu’ici tout va bien", "ça va mal", "c’est fini"], bonneReponse: 0 },
{ question: "in the dark of night", choix: ["dans la nuit noire", "en plein jour", "le matin"], bonneReponse: 0 },
{ question: "the story takes place", choix: ["l’histoire se passe", "l’histoire finit", "l’histoire commence"], bonneReponse: 0 },

{ question: "dwarf", choix: ["nain", "géant", "roi"], bonneReponse: 0 },
{ question: "leprechaun", choix: ["lutin", "sorcier", "fantôme"], bonneReponse: 0 },
{ question: "banshee", choix: ["esprit", "animal", "roi"], bonneReponse: 0 },
{ question: "magician", choix: ["magicien", "soldat", "roi"], bonneReponse: 0 },
{ question: "sorcerer", choix: ["sorcier", "chevalier", "paysan"], bonneReponse: 0 },

{ question: "poison", choix: ["poison", "médicament", "eau"], bonneReponse: 0 },

{ question: "to kill", choix: ["tuer", "aider", "sauver"], bonneReponse: 0 },
{ question: "to frighten", choix: ["effrayer", "amuser", "calmer"], bonneReponse: 0 },
{ question: "to fall in love", choix: ["tomber amoureux", "se fâcher", "partir"], bonneReponse: 0 },
{ question: "to discover", choix: ["découvrir", "cacher", "perdre"], bonneReponse: 0 },

{ question: "tense", choix: ["stressé", "calme", "heureux"], bonneReponse: 0 },
{ question: "disappointed", choix: ["déçu", "content", "heureux"], bonneReponse: 0 },
{ question: "cross", choix: ["en colère", "calme", "joyeux"], bonneReponse: 0 },
{ question: "luckily", choix: ["heureusement", "malheureusement", "lentement"], bonneReponse: 0 },
{ question: "fortunately", choix: ["heureusement", "tristement", "vite"], bonneReponse: 0 },
{ question: "sadly", choix: ["tristement", "heureusement", "facilement"], bonneReponse: 0 },
{ question: "unfortunately", choix: ["malheureusement", "heureusement", "rapidement"], bonneReponse: 0 },

{ question: "timetable", choix: ["emploi du temps", "calendrier", "horloge"], bonneReponse: 0 },
{ question: "schedule", choix: ["planning", "pause", "vacances"], bonneReponse: 0 },
{ question: "school subjects", choix: ["matières scolaires", "jeux", "sports"], bonneReponse: 0 },
{ question: "club", choix: ["club", "classe", "école"], bonneReponse: 0 },
{ question: "classmate", choix: ["camarade de classe", "prof", "parent"], bonneReponse: 0 },
{ question: "to learn", choix: ["apprendre", "enseigner", "oublier"], bonneReponse: 0 },
{ question: "be a member of", choix: ["être membre de", "quitter", "refuser"], bonneReponse: 0 },
{ question: "hobbies", choix: ["loisirs", "travail", "cours"], bonneReponse: 0 },
{ question: "pastime", choix: ["passe-temps", "devoir", "travail"], bonneReponse: 0 },
{ question: "leisure", choix: ["temps libre", "travail", "école"], bonneReponse: 0 },
{ question: "education", choix: ["éducation", "jeu", "repos"], bonneReponse: 0 },
{ question: "out-of-school", choix: ["hors école", "en classe", "chez soi"], bonneReponse: 0 },
{ question: "clique", choix: ["groupe", "ennemi", "prof"], bonneReponse: 0 },
{ question: "workshop", choix: ["atelier", "bureau", "maison"], bonneReponse: 0 },
{ question: "daily", choix: ["quotidien", "mensuel", "annuel"], bonneReponse: 0 },
{ question: "weekly", choix: ["hebdomadaire", "quotidien", "annuel"], bonneReponse: 0 },

{ question: "proud", choix: ["fier", "honteux", "triste"], bonneReponse: 0 },
{ question: "slim", choix: ["mince", "gros", "grand"], bonneReponse: 0 },
{ question: "huge", choix: ["énorme", "petit", "fin"], bonneReponse: 0 },
{ question: "smart", choix: ["intelligent", "bête", "lent"], bonneReponse: 0 },
{ question: "features", choix: ["traits du visage", "vêtements", "objets"], bonneReponse: 0 },
{ question: "nice", choix: ["gentil", "méchant", "froid"], bonneReponse: 0 },
{ question: "expressive", choix: ["expressif", "fermé", "calme"], bonneReponse: 0 },
{ question: "generous", choix: ["généreux", "égoïste", "méchant"], bonneReponse: 0 },
{ question: "honest", choix: ["honnête", "menteur", "faux"], bonneReponse: 0 },
{ question: "polite", choix: ["poli", "impoli", "bruyant"], bonneReponse: 0 },
{ question: "cheery", choix: ["joyeux", "triste", "fatigué"], bonneReponse: 0 },

{ question: "to travel", choix: ["voyager", "rester", "travailler"], bonneReponse: 0 },
{ question: "to go on a trip", choix: ["partir en voyage", "rentrer", "étudier"], bonneReponse: 0 },
{ question: "globetrotting", choix: ["faire le tour du monde", "travailler", "rester"], bonneReponse: 0 },
{ question: "public transport", choix: ["transports publics", "voiture", "vélo"], bonneReponse: 0 },
{ question: "coach", choix: ["car", "train", "bus"], bonneReponse: 0 },
{ question: "to move", choix: ["déménager", "rester", "dormir"], bonneReponse: 0 },
{ question: "camper van", choix: ["camping-car", "voiture", "bus"], bonneReponse: 0 },
{ question: "underground", choix: ["métro", "bus", "tram"], bonneReponse: 0 },
{ question: "subway", choix: ["métro", "bus", "taxi"], bonneReponse: 0 },
{ question: "traffic", choix: ["circulation", "route", "chemin"], bonneReponse: 0 },
{ question: "far", choix: ["loin", "près", "ici"], bonneReponse: 0 },
{ question: "close", choix: ["près", "loin", "partout"], bonneReponse: 0 },

{ question: "seasonal", choix: ["saisonnier", "quotidien", "ancien"], bonneReponse: 0 },
{ question: "pure", choix: ["pur", "sale", "mélangé"], bonneReponse: 0 },
{ question: "colourful", choix: ["coloré", "gris", "sombre"], bonneReponse: 0 },
{ question: "changing", choix: ["changeant", "fixe", "stable"], bonneReponse: 0 },
{ question: "climate", choix: ["climat", "saison", "temps"], bonneReponse: 0 },
{ question: "forest", choix: ["forêt", "plage", "ville"], bonneReponse: 0 },
{ question: "desert", choix: ["désert", "forêt", "lac"], bonneReponse: 0 },
{ question: "lake", choix: ["lac", "mer", "rivière"], bonneReponse: 0 },
{ question: "rural", choix: ["campagne", "ville", "route"], bonneReponse: 0 },
{ question: "place", choix: ["endroit", "personne", "objet"], bonneReponse: 0 },
{ question: "city centre", choix: ["centre-ville", "banlieue", "village"], bonneReponse: 0 },
{ question: "street", choix: ["rue", "route", "autoroute"], bonneReponse: 0 },
{ question: "land", choix: ["terre", "mer", "ciel"], bonneReponse: 0 },
{ question: "vast", choix: ["immense", "petit", "court"], bonneReponse: 0 },
{ question: "road", choix: ["route", "chemin", "pont"], bonneReponse: 0 },
{ question: "museum", choix: ["musée", "école", "magasin"], bonneReponse: 0 },
{ question: "monument", choix: ["monument", "maison", "pont"], bonneReponse: 0 },
{ question: "cottage", choix: ["petite maison", "immeuble", "château"], bonneReponse: 0 },

{ question: "cook", choix: ["cuisiner", "manger", "boire"], bonneReponse: 0 },
{ question: "speciality", choix: ["spécialité", "dessert", "entrée"], bonneReponse: 0 },
{ question: "typical", choix: ["typique", "rare", "étrange"], bonneReponse: 0 },
{ question: "traditional", choix: ["traditionnel", "moderne", "nouveau"], bonneReponse: 0 },
{ question: "baking", choix: ["pâtisserie", "cuisine", "boisson"], bonneReponse: 0 },
{ question: "dish", choix: ["plat", "verre", "table"], bonneReponse: 0 },
{ question: "family meal", choix: ["repas de famille", "petit-déjeuner", "goûter"], bonneReponse: 0 },
{ question: "fork", choix: ["fourchette", "cuillère", "couteau"], bonneReponse: 0 },
{ question: "knife", choix: ["couteau", "fourchette", "verre"], bonneReponse: 0 },
{ question: "plate", choix: ["assiette", "verre", "table"], bonneReponse: 0 },
{ question: "together", choix: ["ensemble", "seul", "loin"], bonneReponse: 0 },

{ question: "photographer", choix: ["photographe", "peintre", "acteur"], bonneReponse: 0 },
{ question: "architecture", choix: ["architecture", "peinture", "musique"], bonneReponse: 0 },
{ question: "picture", choix: ["image", "texte", "musique"], bonneReponse: 0 },
{ question: "illustration", choix: ["illustration", "texte", "photo"], bonneReponse: 0 },
{ question: "portrait", choix: ["portrait", "paysage", "dessin"], bonneReponse: 0 },
{ question: "dark", choix: ["sombre", "clair", "coloré"], bonneReponse: 0 },
{ question: "bright", choix: ["lumineux", "sombre", "gris"], bonneReponse: 0 },
{ question: "message", choix: ["message", "image", "objet"], bonneReponse: 0 },
{ question: "goal", choix: ["objectif", "jeu", "score"], bonneReponse: 0 },
{ question: "to represent", choix: ["représenter", "cacher", "oublier"], bonneReponse: 0 },
{ question: "to contemplate", choix: ["observer", "ignorer", "quitter"], bonneReponse: 0 },
{ question: "to explore", choix: ["explorer", "éviter", "fermer"], bonneReponse: 0 },
{ question: "international", choix: ["international", "local", "national"], bonneReponse: 0 },
{ question: "to find yourself", choix: ["se découvrir", "se perdre", "se cacher"], bonneReponse: 0 },
{ question: "way", choix: ["chemin", "route", "direction"], bonneReponse: 0 },
{ question: "to experience", choix: ["expérimenter", "éviter", "ignorer"], bonneReponse: 0 },
{ question: "expedition", choix: ["expédition", "voyage", "sortie"], bonneReponse: 0 },

{ question: "tale", choix: ["conte", "histoire vraie", "film"], bonneReponse: 0 },
{ question: "courageous", choix: ["courageux", "peureux", "faible"], bonneReponse: 0 },
{ question: "to imagine", choix: ["imaginer", "voir", "oublier"], bonneReponse: 0 },
{ question: "imaginary", choix: ["imaginaire", "réel", "vrai"], bonneReponse: 0 },
{ question: "vision", choix: ["vision", "rêve", "idée"], bonneReponse: 0 },
{ question: "image", choix: ["image", "texte", "son"], bonneReponse: 0 },
{ question: "real", choix: ["réel", "faux", "imaginaire"], bonneReponse: 0 },
{ question: "unreal", choix: ["irréel", "vrai", "réel"], bonneReponse: 0 },
{ question: "hope", choix: ["espoir", "peur", "tristesse"], bonneReponse: 0 },
{ question: "desire", choix: ["désir", "peur", "haine"], bonneReponse: 0 },
{ question: "enchanting", choix: ["enchanteur", "ennuyeux", "triste"], bonneReponse: 0 },
{ question: "wonderland", choix: ["monde magique", "ville", "pays"], bonneReponse: 0 },
{ question: "heaven", choix: ["paradis", "enfer", "terre"], bonneReponse: 0 },
{ question: "illusion", choix: ["illusion", "vérité", "fait"], bonneReponse: 0 },
{ question: "legend", choix: ["légende", "histoire", "conte"], bonneReponse: 0 },
{ question: "hero", choix: ["héros", "méchant", "roi"], bonneReponse: 0 },
{ question: "heroine", choix: ["héroïne", "reine", "princesse"], bonneReponse: 0 },

{ question: "Wow!", choix: ["waouh", "beurk", "miam"], bonneReponse: 0 },
{ question: "Yummy!", choix: ["miam", "beurk", "zut"], bonneReponse: 0 },
{ question: "Yuk!", choix: ["beurk", "miam", "super"], bonneReponse: 0 },
{ question: "extraordinary", choix: ["extraordinaire", "normal", "simple"], bonneReponse: 0 },

{ question: "to like", choix: ["aimer", "détester", "ignorer"], bonneReponse: 0 },
{ question: "beauty", choix: ["beauté", "laideur", "tristesse"], bonneReponse: 0 },
{ question: "joy", choix: ["joie", "tristesse", "peur"], bonneReponse: 0 },
{ question: "sadness", choix: ["tristesse", "joie", "colère"], bonneReponse: 0 }

];
