const quiz = [ /* questions 6e */ 

{ question: "family", choix: ["famille", "ami", "voisin"], bonneReponse: 0 },
{ question: "parents", choix: ["enfants", "parents", "amis"], bonneReponse: 1 },
{ question: "mother", choix: ["mère", "tante", "sœur"], bonneReponse: 0 },
{ question: "father", choix: ["frère", "père", "oncle"], bonneReponse: 1 },
{ question: "brother", choix: ["cousin", "frère", "ami"], bonneReponse: 1 },
{ question: "sister", choix: ["sœur", "nièce", "tante"], bonneReponse: 0 },
{ question: "uncle", choix: ["père", "oncle", "grand-père"], bonneReponse: 1 },
{ question: "aunt", choix: ["tante", "sœur", "cousine"], bonneReponse: 0 },
{ question: "cousin", choix: ["ami", "cousin", "voisin"], bonneReponse: 1 },
{ question: "child", choix: ["bébé", "enfant", "adulte"], bonneReponse: 1 },
{ question: "children", choix: ["adultes", "enfants", "parents"], bonneReponse: 1 },

{ question: "British", choix: ["anglais", "britannique", "américain"], bonneReponse: 1 },
{ question: "English", choix: ["anglais", "français", "irlandais"], bonneReponse: 0 },
{ question: "Irish", choix: ["écossais", "irlandais", "gallois"], bonneReponse: 1 },
{ question: "Scottish", choix: ["écossais", "anglais", "irlandais"], bonneReponse: 0 },
{ question: "Welsh", choix: ["gallois", "écossais", "anglais"], bonneReponse: 0 },
{ question: "American", choix: ["canadien", "américain", "mexicain"], bonneReponse: 1 },
{ question: "Australian", choix: ["australien", "anglais", "néo-zélandais"], bonneReponse: 0 },
{ question: "South African", choix: ["sud-africain", "américain", "australien"], bonneReponse: 0 },
{ question: "Canadian", choix: ["canadien", "américain", "anglais"], bonneReponse: 0 },
{ question: "Indian", choix: ["indien", "chinois", "japonais"], bonneReponse: 0 },
{ question: "French", choix: ["français", "italien", "espagnol"], bonneReponse: 0 },

{ question: "big", choix: ["grand", "petit", "court"], bonneReponse: 0 },
{ question: "tall", choix: ["grand (taille)", "petit", "mince"], bonneReponse: 0 },
{ question: "small", choix: ["grand", "petit", "énorme"], bonneReponse: 1 },
{ question: "young", choix: ["vieux", "jeune", "grand"], bonneReponse: 1 },
{ question: "old", choix: ["jeune", "vieux", "neuf"], bonneReponse: 1 },
{ question: "skinny", choix: ["mince", "gros", "grand"], bonneReponse: 0 },
{ question: "short hair", choix: ["cheveux courts", "cheveux longs", "chauve"], bonneReponse: 0 },
{ question: "long hair", choix: ["cheveux longs", "cheveux courts", "chauve"], bonneReponse: 0 },
{ question: "blond", choix: ["blond", "brun", "roux"], bonneReponse: 0 },
{ question: "funny", choix: ["drôle", "triste", "ennuyeux"], bonneReponse: 0 },
{ question: "intelligent", choix: ["bête", "intelligent", "lent"], bonneReponse: 1 },
{ question: "smart", choix: ["intelligent", "stupide", "lent"], bonneReponse: 0 },
{ question: "adorable", choix: ["adorable", "méchant", "laid"], bonneReponse: 0 },
{ question: "sporty", choix: ["sportif", "paresseux", "lent"], bonneReponse: 0 },
{ question: "nice", choix: ["gentil", "méchant", "triste"], bonneReponse: 0 },
{ question: "beautiful", choix: ["moche", "beau/belle", "sale"], bonneReponse: 1 },

{ question: "t-shirt", choix: ["t-shirt", "pantalon", "pull"], bonneReponse: 0 },
{ question: "trousers", choix: ["pantalon", "jupe", "short"], bonneReponse: 0 },
{ question: "jeans", choix: ["jupe", "jean", "short"], bonneReponse: 1 },
{ question: "pullover", choix: ["pull", "t-shirt", "veste"], bonneReponse: 0 },
{ question: "shoes", choix: ["chaussures", "chaussettes", "chapeau"], bonneReponse: 0 },
{ question: "shirt", choix: ["chemise", "t-shirt", "pull"], bonneReponse: 0 },
{ question: "socks", choix: ["chaussettes", "chaussures", "gants"], bonneReponse: 0 },
{ question: "hat", choix: ["chapeau", "casquette", "bonnet"], bonneReponse: 0 },
{ question: "cap", choix: ["casquette", "chapeau", "bonnet"], bonneReponse: 0 },
{ question: "coat", choix: ["manteau", "veste", "pull"], bonneReponse: 0 },
{ question: "jacket", choix: ["veste", "manteau", "pull"], bonneReponse: 0 },
{ question: "skirt", choix: ["jupe", "robe", "short"], bonneReponse: 0 },

{ question: "head", choix: ["tête", "bras", "main"], bonneReponse: 0 },
{ question: "arms", choix: ["bras", "jambes", "mains"], bonneReponse: 0 },
{ question: "foot", choix: ["pied", "main", "jambe"], bonneReponse: 0 },
{ question: "feet", choix: ["pieds", "mains", "bras"], bonneReponse: 0 },
{ question: "hair", choix: ["cheveux", "yeux", "nez"], bonneReponse: 0 },
{ question: "eyes", choix: ["yeux", "oreilles", "nez"], bonneReponse: 0 },
{ question: "ears", choix: ["oreilles", "yeux", "nez"], bonneReponse: 0 },
{ question: "hands", choix: ["mains", "pieds", "bras"], bonneReponse: 0 },
{ question: "fingers", choix: ["doigts", "orteils", "mains"], bonneReponse: 0 },
{ question: "legs", choix: ["jambes", "bras", "dos"], bonneReponse: 0 },
{ question: "mouth", choix: ["nez", "bouche", "oreille"], bonneReponse: 1 },
{ question: "face", choix: ["visage", "main", "dos"], bonneReponse: 0 },
{ question: "body", choix: ["corps", "tête", "bras"], bonneReponse: 0 },

/* JOBS */
{ question: "work", choix: ["travail", "école", "jeu"], bonneReponse: 0 },
{ question: "a policeman", choix: ["policier", "professeur", "médecin"], bonneReponse: 0 },
{ question: "a teacher", choix: ["professeur", "docteur", "policier"], bonneReponse: 0 },
{ question: "a pilot", choix: ["pilote", "chauffeur", "mécanicien"], bonneReponse: 0 },
{ question: "a driver", choix: ["chauffeur", "pilote", "vendeur"], bonneReponse: 0 },
{ question: "an engineer", choix: ["ingénieur", "ouvrier", "vendeur"], bonneReponse: 0 },
{ question: "a secretary", choix: ["secrétaire", "directeur", "professeur"], bonneReponse: 0 },
{ question: "a doctor", choix: ["infirmier", "médecin", "dentiste"], bonneReponse: 1 },
{ question: "a dentist", choix: ["dentiste", "médecin", "infirmier"], bonneReponse: 0 },
{ question: "a veterinary", choix: ["vétérinaire", "médecin", "infirmier"], bonneReponse: 0 },
{ question: "an actor", choix: ["acteur", "chanteur", "danseur"], bonneReponse: 0 },
{ question: "an actress", choix: ["actrice", "chanteuse", "danseuse"], bonneReponse: 0 },
{ question: "a farmer", choix: ["fermier", "ouvrier", "vendeur"], bonneReponse: 0 },

/* ANIMALS */
{ question: "dog", choix: ["chat", "chien", "lapin"], bonneReponse: 1 },
{ question: "cat", choix: ["chien", "chat", "souris"], bonneReponse: 1 },
{ question: "rabbit", choix: ["lapin", "hamster", "rat"], bonneReponse: 0 },
{ question: "horse", choix: ["cheval", "vache", "cochon"], bonneReponse: 0 },
{ question: "mouse", choix: ["souris", "rat", "chat"], bonneReponse: 0 },
{ question: "hamster", choix: ["hamster", "lapin", "chien"], bonneReponse: 0 },
{ question: "guinea pig", choix: ["cochon d’Inde", "lapin", "rat"], bonneReponse: 0 },
{ question: "chicken", choix: ["poulet", "canard", "dinde"], bonneReponse: 0 },
{ question: "hen", choix: ["poule", "coq", "canard"], bonneReponse: 0 },
{ question: "sheep", choix: ["mouton", "chèvre", "vache"], bonneReponse: 0 },
{ question: "pig", choix: ["cochon", "vache", "mouton"], bonneReponse: 0 },
{ question: "cow", choix: ["vache", "cheval", "cochon"], bonneReponse: 0 },

/* DAILY ROUTINE */
{ question: "to sleep", choix: ["manger", "dormir", "courir"], bonneReponse: 1 },
{ question: "to wake up", choix: ["se réveiller", "se coucher", "manger"], bonneReponse: 0 },
{ question: "to get up", choix: ["se lever", "dormir", "s’asseoir"], bonneReponse: 0 },
{ question: "to eat", choix: ["boire", "manger", "jouer"], bonneReponse: 1 },
{ question: "to have a shower", choix: ["prendre une douche", "manger", "dormir"], bonneReponse: 0 },
{ question: "to have a bath", choix: ["prendre un bain", "se lever", "courir"], bonneReponse: 0 },
{ question: "to have breakfast", choix: ["prendre le petit-déjeuner", "déjeuner", "dîner"], bonneReponse: 0 },
{ question: "to have lunch", choix: ["déjeuner", "dîner", "petit-déjeuner"], bonneReponse: 0 },
{ question: "to play", choix: ["jouer", "travailler", "lire"], bonneReponse: 0 },
{ question: "to go to school", choix: ["aller à l’école", "dormir", "travailler"], bonneReponse: 0 },
{ question: "to do one’s homework", choix: ["faire ses devoirs", "jouer", "manger"], bonneReponse: 0 },
{ question: "to go to bed", choix: ["aller au lit", "se lever", "courir"], bonneReponse: 0 },

/* HOUSE */
{ question: "house", choix: ["maison", "porte", "fenêtre"], bonneReponse: 0 },
{ question: "flat", choix: ["appartement", "maison", "chambre"], bonneReponse: 0 },
{ question: "apartment", choix: ["appartement", "maison", "garage"], bonneReponse: 0 },
{ question: "room", choix: ["pièce", "porte", "toit"], bonneReponse: 0 },
{ question: "bedroom", choix: ["chambre", "garage", "jardin"], bonneReponse: 0 },
{ question: "living-room", choix: ["salon", "cuisine", "chambre"], bonneReponse: 0 },
{ question: "kitchen", choix: ["salon", "chambre", "cuisine"], bonneReponse: 2 },
{ question: "garden", choix: ["jardin", "mur", "toit"], bonneReponse: 0 },
{ question: "window", choix: ["fenêtre", "porte", "mur"], bonneReponse: 0 },
{ question: "door", choix: ["porte", "fenêtre", "toit"], bonneReponse: 0 },
{ question: "wall", choix: ["mur", "sol", "toit"], bonneReponse: 0 },

/* GAMES */
{ question: "player", choix: ["joueur", "jeu", "équipe"], bonneReponse: 0 },
{ question: "card", choix: ["carte", "dé", "plateau"], bonneReponse: 0 },
{ question: "dice", choix: ["dé", "carte", "pion"], bonneReponse: 0 },
{ question: "board game", choix: ["jeu de société", "jeu vidéo", "jeu sportif"], bonneReponse: 0 },
{ question: "it is your turn", choix: ["c’est ton tour", "tu as perdu", "tu gagnes"], bonneReponse: 0 },
{ question: "to start", choix: ["commencer", "finir", "perdre"], bonneReponse: 0 },
{ question: "to win", choix: ["gagner", "perdre", "jouer"], bonneReponse: 0 },
{ question: "to lose", choix: ["perdre", "gagner", "jouer"], bonneReponse: 0 },

/* FOOD */
{ question: "breakfast", choix: ["petit-déjeuner", "déjeuner", "dîner"], bonneReponse: 0 },
{ question: "lunch", choix: ["déjeuner", "dîner", "petit-déjeuner"], bonneReponse: 0 },
{ question: "dinner", choix: ["dîner", "déjeuner", "petit-déjeuner"], bonneReponse: 0 },
{ question: "to be hungry", choix: ["avoir faim", "avoir soif", "être fatigué"], bonneReponse: 0 },
{ question: "to be thirsty", choix: ["avoir soif", "avoir faim", "être fatigué"], bonneReponse: 0 },
{ question: "meat", choix: ["fruit", "viande", "légume"], bonneReponse: 1 },
{ question: "vegetables", choix: ["légumes", "fruits", "viande"], bonneReponse: 0 },
{ question: "tomato", choix: ["tomate", "pomme", "carotte"], bonneReponse: 0 },
{ question: "cucumber", choix: ["concombre", "carotte", "tomate"], bonneReponse: 0 },
{ question: "zucchini", choix: ["courgette", "aubergine", "carotte"], bonneReponse: 0 },
{ question: "fruit", choix: ["légumes", "fruits", "desserts"], bonneReponse: 1 },
{ question: "pear", choix: ["poire", "pomme", "pêche"], bonneReponse: 0 },
{ question: "apricot", choix: ["abricot", "pêche", "prune"], bonneReponse: 0 },
{ question: "pineapple", choix: ["ananas", "banane", "orange"], bonneReponse: 0 },
{ question: "cake", choix: ["pain", "gâteau", "fromage"], bonneReponse: 1 },
{ question: "sugar", choix: ["sucre", "sel", "farine"], bonneReponse: 0 },

/* LOISIRS & LIEUX */
{ question: "cinema", choix: ["cinéma", "théâtre", "école"], bonneReponse: 0 },
{ question: "bowling", choix: ["bowling", "football", "tennis"], bonneReponse: 0 },
{ question: "swimming-pool", choix: ["piscine", "lac", "mer"], bonneReponse: 0 },
{ question: "skating rink", choix: ["patinoire", "stade", "gymnase"], bonneReponse: 0 },
{ question: "stadium", choix: ["stade", "cinéma", "école"], bonneReponse: 0 },
{ question: "gym", choix: ["salle de sport", "école", "cinéma"], bonneReponse: 0 },

/* LOISIRS */
{ question: "reading", choix: ["lecture", "écriture", "dessin"], bonneReponse: 0 },
{ question: "doing sport", choix: ["faire du sport", "dormir", "manger"], bonneReponse: 0 },
{ question: "listening to music", choix: ["écouter de la musique", "chanter", "danser"], bonneReponse: 0 },
{ question: "dancing", choix: ["danser", "chanter", "courir"], bonneReponse: 0 },
{ question: "playing tennis", choix: ["jouer au tennis", "jouer au foot", "jouer au basket"], bonneReponse: 0 },
{ question: "playing an instrument", choix: ["jouer d’un instrument", "chanter", "danser"], bonneReponse: 0 },
{ question: "singing", choix: ["chanter", "danser", "courir"], bonneReponse: 0 },
{ question: "horse-riding", choix: ["faire du cheval", "courir", "nager"], bonneReponse: 0 },

/* TEMPS */
{ question: "at the weekend", choix: ["le week-end", "le matin", "le soir"], bonneReponse: 0 },
{ question: "in the morning", choix: ["le matin", "le soir", "la nuit"], bonneReponse: 0 },
{ question: "after school", choix: ["après l’école", "avant l’école", "pendant l’école"], bonneReponse: 0 },
{ question: "every week", choix: ["chaque semaine", "chaque jour", "chaque mois"], bonneReponse: 0 },

/* FÊTES */
{ question: "Thanksgiving", choix: ["Thanksgiving", "Noël", "Pâques"], bonneReponse: 0 },
{ question: "Christmas Eve", choix: ["veille de Noël", "jour de Noël", "Nouvel An"], bonneReponse: 0 },
{ question: "Christmas Day", choix: ["jour de Noël", "veille de Noël", "Nouvel An"], bonneReponse: 0 },
{ question: "turkey", choix: ["dinde", "poulet", "canard"], bonneReponse: 0 },
{ question: "pudding", choix: ["pudding", "gâteau", "pain"], bonneReponse: 0 },
{ question: "crackers", choix: ["crackers", "bonbons", "gâteaux"], bonneReponse: 0 },
{ question: "presents", choix: ["cadeaux", "jouets", "vêtements"], bonneReponse: 0 },
{ question: "Christmas Carol", choix: ["chant de Noël", "film", "jeu"], bonneReponse: 0 },
{ question: "New Year’s Day", choix: ["jour de l’an", "veille de Noël", "anniversaire"], bonneReponse: 0 },
{ question: "Saint Patrick’s Day", choix: ["Saint Patrick", "Noël", "Halloween"], bonneReponse: 0 },

/* GÉOGRAPHIE */
{ question: "country", choix: ["pays", "ville", "continent"], bonneReponse: 0 },
{ question: "state", choix: ["état", "ville", "région"], bonneReponse: 0 },
{ question: "union", choix: ["union", "division", "groupe"], bonneReponse: 0 },
{ question: "island", choix: ["île", "continent", "pays"], bonneReponse: 0 },
{ question: "isle", choix: ["île", "lac", "mer"], bonneReponse: 0 },
{ question: "continent", choix: ["continent", "pays", "ville"], bonneReponse: 0 },
{ question: "ocean", choix: ["océan", "mer", "lac"], bonneReponse: 0 },
{ question: "sea", choix: ["mer", "océan", "lac"], bonneReponse: 0 },
{ question: "lake", choix: ["lac", "mer", "rivière"], bonneReponse: 0 },
{ question: "coast", choix: ["côte", "montagne", "forêt"], bonneReponse: 0 },
{ question: "beach", choix: ["plage", "forêt", "montagne"], bonneReponse: 0 },
{ question: "forest", choix: ["forêt", "plage", "désert"], bonneReponse: 0 },
{ question: "mountains", choix: ["montagnes", "plaines", "désert"], bonneReponse: 0 },
{ question: "desert", choix: ["désert", "forêt", "lac"], bonneReponse: 0 },
{ question: "river", choix: ["rivière", "lac", "mer"], bonneReponse: 0 },
{ question: "landscape", choix: ["paysage", "ville", "pays"], bonneReponse: 0 },
{ question: "colourful", choix: ["coloré", "triste", "sombre"], bonneReponse: 0 },
{ question: "vast", choix: ["vaste", "petit", "étroit"], bonneReponse: 0 },

/* IMAGINAIRE */
{ question: "fairy tale", choix: ["conte de fées", "histoire", "film"], bonneReponse: 0 },
{ question: "story", choix: ["histoire", "film", "jeu"], bonneReponse: 0 },
{ question: "legend", choix: ["légende", "histoire", "conte"], bonneReponse: 0 },
{ question: "witch", choix: ["sorcière", "magicien", "fantôme"], bonneReponse: 0 },
{ question: "magic", choix: ["magie", "science", "jeu"], bonneReponse: 0 },
{ question: "magician", choix: ["magicien", "acteur", "chanteur"], bonneReponse: 0 },
{ question: "haunted castle", choix: ["château hanté", "maison", "forêt"], bonneReponse: 0 },
{ question: "far away", choix: ["loin", "près", "ici"], bonneReponse: 0 },
{ question: "isolated", choix: ["isolé", "occupé", "plein"], bonneReponse: 0 },

/* ÉMOTIONS */
{ question: "happy", choix: ["triste", "content", "fatigué"], bonneReponse: 1 },
{ question: "sad", choix: ["heureux", "triste", "énervé"], bonneReponse: 1 },
{ question: "tired", choix: ["fatigué", "heureux", "énervé"], bonneReponse: 0 },
{ question: "angry", choix: ["calme", "énervé", "joyeux"], bonneReponse: 1 },
{ question: "surprised", choix: ["surpris", "triste", "fatigué"], bonneReponse: 0 },
{ question: "afraid", choix: ["effrayé", "courageux", "content"], bonneReponse: 0 },
{ question: "scared", choix: ["effrayé", "heureux", "calme"], bonneReponse: 0 },

/* EXPRESSIONS */
{ question: "great!", choix: ["super !", "nul !", "triste !"], bonneReponse: 0 },
{ question: "wonderful!", choix: ["merveilleux !", "horrible !", "triste !"], bonneReponse: 0 },
{ question: "I’m glad", choix: ["je suis content", "je suis triste", "je suis fatigué"], bonneReponse: 0 },
{ question: "what a shame", choix: ["quel dommage", "super", "bravo"], bonneReponse: 0 },
  
];

