const quiz = [

{ question: "stick", choix: ["crosse", "balle", "filet"], bonneReponse: 0 },
{ question: "puck", choix: ["palet", "balle", "raquette"], bonneReponse: 0 },
{ question: "net", choix: ["filet", "but", "terrain"], bonneReponse: 0 },
{ question: "goal", choix: ["but", "filet", "match"], bonneReponse: 0 },
{ question: "mouthguard", choix: ["protège-dents", "casque", "gants"], bonneReponse: 0 },

{ question: "to support", choix: ["soutenir", "abandonner", "ignorer"], bonneReponse: 0 },
{ question: "to train", choix: ["s'entraîner", "jouer", "regarder"], bonneReponse: 0 },
{ question: "to cheer", choix: ["encourager", "critiquer", "ignorer"], bonneReponse: 0 },
{ question: "hall of fame", choix: ["panthéon sportif", "stade", "musée"], bonneReponse: 0 },

{ question: "arrogant", choix: ["arrogant", "modeste", "timide"], bonneReponse: 0 },
{ question: "slender", choix: ["mince", "gros", "petit"], bonneReponse: 0 },
{ question: "tiny", choix: ["minuscule", "grand", "moyen"], bonneReponse: 0 },
{ question: "fit", choix: ["en forme", "fatigué", "malade"], bonneReponse: 0 },
{ question: "in good shape", choix: ["en bonne forme", "malade", "fatigué"], bonneReponse: 0 },
{ question: "open-minded", choix: ["ouvert d'esprit", "fermé", "strict"], bonneReponse: 0 },
{ question: "eager", choix: ["impatient", "désintéressé", "fatigué"], bonneReponse: 0 },
{ question: "reasonable", choix: ["raisonnable", "injuste", "méchant"], bonneReponse: 0 },
{ question: "bad-mannered", choix: ["mal élevé", "poli", "gentil"], bonneReponse: 0 },

{ question: "trip", choix: ["voyage", "travail", "maison"], bonneReponse: 0 },
{ question: "journey", choix: ["voyage", "trajet", "pause"], bonneReponse: 0 },
{ question: "traffic jam", choix: ["embouteillage", "route", "autoroute"], bonneReponse: 0 },
{ question: "to take in the sights", choix: ["visiter", "travailler", "conduire"], bonneReponse: 0 },
{ question: "rideshare", choix: ["covoiturage", "bus", "taxi"], bonneReponse: 0 },
{ question: "convenience", choix: ["commodité", "difficulté", "problème"], bonneReponse: 0 },
{ question: "far off", choix: ["loin", "près", "à côté"], bonneReponse: 0 },
{ question: "adjacent", choix: ["adjacent", "éloigné", "séparé"], bonneReponse: 0 },

{ question: "blooming", choix: ["en fleurs", "sec", "mort"], bonneReponse: 0 },
{ question: "rainfall", choix: ["précipitations", "vent", "chaleur"], bonneReponse: 0 },
{ question: "yearly", choix: ["annuel", "mensuel", "quotidien"], bonneReponse: 0 },
{ question: "harshness", choix: ["rudesse", "douceur", "chaleur"], bonneReponse: 0 },
{ question: "bright", choix: ["lumineux", "sombre", "gris"], bonneReponse: 0 },
{ question: "dim", choix: ["faible", "lumineux", "clair"], bonneReponse: 0 },
{ question: "stifling", choix: ["étouffant", "frais", "agréable"], bonneReponse: 0 },
{ question: "harvest", choix: ["récolte", "plantation", "culture"], bonneReponse: 0 },
{ question: "weeds", choix: ["mauvaises herbes", "fleurs", "arbres"], bonneReponse: 0 },
{ question: "inland", choix: ["à l'intérieur des terres", "côtier", "maritime"], bonneReponse: 0 },

{ question: "location", choix: ["lieu", "voyage", "carte"], bonneReponse: 0 },
{ question: "alley", choix: ["ruelle", "avenue", "route"], bonneReponse: 0 },
{ question: "downtown", choix: ["centre-ville", "banlieue", "campagne"], bonneReponse: 0 },
{ question: "suburbs", choix: ["banlieue", "centre-ville", "campagne"], bonneReponse: 0 },
{ question: "neighbourhood", choix: ["quartier", "ville", "région"], bonneReponse: 0 },
{ question: "countryside", choix: ["campagne", "ville", "banlieue"], bonneReponse: 0 },
{ question: "river bank", choix: ["rive", "montagne", "forêt"], bonneReponse: 0 },
{ question: "stream", choix: ["ruisseau", "fleuve", "mer"], bonneReponse: 0 },
{ question: "pond", choix: ["étang", "lac", "rivière"], bonneReponse: 0 },
{ question: "cityscape", choix: ["paysage urbain", "campagne", "forêt"], bonneReponse: 0 },

{ question: "visionary", choix: ["visionnaire", "réaliste", "timide"], bonneReponse: 0 },
{ question: "environmentally friendly", choix: ["écologique", "polluant", "sale"], bonneReponse: 0 },
{ question: "to come up with an idea", choix: ["trouver une idée", "oublier", "copier"], bonneReponse: 0 },
{ question: "to discover", choix: ["découvrir", "cacher", "perdre"], bonneReponse: 0 },
{ question: "to experiment", choix: ["expérimenter", "observer", "copier"], bonneReponse: 0 },
{ question: "to improve", choix: ["améliorer", "détruire", "arrêter"], bonneReponse: 0 },

{ question: "character", choix: ["personnage", "acteur", "scène"], bonneReponse: 0 },
{ question: "scenery", choix: ["décor", "personnage", "histoire"], bonneReponse: 0 },
{ question: "setting", choix: ["cadre", "acteur", "objet"], bonneReponse: 0 },
{ question: "portrayal", choix: ["représentation", "histoire", "acteur"], bonneReponse: 0 },
{ question: "art movement", choix: ["mouvement artistique", "tableau", "musée"], bonneReponse: 0 },

{ question: "to long for", choix: ["désirer", "refuser", "oublier"], bonneReponse: 0 },
{ question: "strange", choix: ["étrange", "normal", "habituel"], bonneReponse: 0 },
{ question: "wonderful", choix: ["merveilleux", "horrible", "triste"], bonneReponse: 0 },
{ question: "weird", choix: ["bizarre", "normal", "simple"], bonneReponse: 0 },
{ question: "utopia", choix: ["utopie", "réalité", "ville"], bonneReponse: 0 },

{ question: "to enjoy", choix: ["apprécier", "détester", "ignorer"], bonneReponse: 0 },
{ question: "to dislike", choix: ["ne pas aimer", "adorer", "aimer"], bonneReponse: 0 },
{ question: "to appreciate", choix: ["apprécier", "ignorer", "refuser"], bonneReponse: 0 },
{ question: "to feel", choix: ["ressentir", "penser", "voir"], bonneReponse: 0 },
{ question: "to be keen on", choix: ["aimer beaucoup", "détester", "ignorer"], bonneReponse: 0 },
{ question: "to be fond of", choix: ["aimer", "haïr", "refuser"], bonneReponse: 0 },
{ question: "can’t stand", choix: ["ne pas supporter", "aimer", "adorer"], bonneReponse: 0 },

{ question: "gloom", choix: ["tristesse", "joie", "colère"], bonneReponse: 0 },
{ question: "sorrow", choix: ["chagrin", "bonheur", "plaisir"], bonneReponse: 0 },
{ question: "amazement", choix: ["émerveillement", "ennui", "tristesse"], bonneReponse: 0 },

{ question: "innovation", choix: ["innovation", "tradition", "habitude"], bonneReponse: 0 },

{ question: "to realise", choix: ["se rendre compte", "oublier", "penser"], bonneReponse: 0 },
{ question: "to end up", choix: ["finir par", "commencer", "continuer"], bonneReponse: 0 },
{ question: "to trek", choix: ["marcher longtemps", "courir", "voler"], bonneReponse: 0 },
{ question: "perilous", choix: ["dangereux", "sûr", "facile"], bonneReponse: 0 },
{ question: "risky", choix: ["risqué", "sûr", "facile"], bonneReponse: 0 },

{ question: "peer pressure", choix: ["pression des pairs", "amitié", "famille"], bonneReponse: 0 },
{ question: "to apologise", choix: ["s'excuser", "accuser", "refuser"], bonneReponse: 0 },
{ question: "soulmate", choix: ["âme sœur", "ami", "voisin"], bonneReponse: 0 },
{ question: "sidekick", choix: ["acolyte", "ennemi", "chef"], bonneReponse: 0 },

{ question: "to raise awareness", choix: ["sensibiliser", "ignorer", "cacher"], bonneReponse: 0 },
{ question: "to advocate", choix: ["défendre", "attaquer", "ignorer"], bonneReponse: 0 },
{ question: "strike", choix: ["grève", "travail", "réunion"], bonneReponse: 0 },
{ question: "demonstration", choix: ["manifestation", "travail", "réunion"], bonneReponse: 0 },
{ question: "sustainability", choix: ["durabilité", "pollution", "consommation"], bonneReponse: 0 },

{ question: "child labour", choix: ["travail des enfants", "école", "jeu"], bonneReponse: 0 },
{ question: "gender stereotypes", choix: ["stéréotypes de genre", "égalité", "justice"], bonneReponse: 0 },
{ question: "sweatshops", choix: ["ateliers clandestins", "usines", "bureaux"], bonneReponse: 0 },

{ question: "teamwork", choix: ["travail d'équipe", "travail seul", "compétition"], bonneReponse: 0 },
{ question: "resort", choix: ["station touristique", "ville", "campagne"], bonneReponse: 0 },
{ question: "tourist trap", choix: ["piège à touristes", "musée", "monument"], bonneReponse: 0 },

{ question: "to wander", choix: ["errer", "courir", "travailler"], bonneReponse: 0 },
{ question: "to hitchhike", choix: ["faire du stop", "conduire", "marcher"], bonneReponse: 0 },
{ question: "to settle in", choix: ["s'installer", "partir", "voyager"], bonneReponse: 0 },

{ question: "slang", choix: ["argot", "langue officielle", "dialecte"], bonneReponse: 0 },
{ question: "to promote", choix: ["promouvoir", "cacher", "ignorer"], bonneReponse: 0 },
{ question: "to manipulate", choix: ["manipuler", "aider", "soutenir"], bonneReponse: 0 },
{ question: "gossip", choix: ["commérages", "information", "journal"], bonneReponse: 0 },

{ question: "trustworthy", choix: ["digne de confiance", "dangereux", "faible"], bonneReponse: 0 },
{ question: "reliable", choix: ["fiable", "instable", "fragile"], bonneReponse: 0 },
{ question: "self-confident", choix: ["confiant", "timide", "peureux"], bonneReponse: 0 },
{ question: "ambitious", choix: ["ambitieux", "paresseux", "calme"], bonneReponse: 0 },
{ question: "considerate", choix: ["attentionné", "égoïste", "méchant"], bonneReponse: 0 },
{ question: "self-centred", choix: ["égocentrique", "généreux", "gentil"], bonneReponse: 0 },

{ question: "skyline", choix: ["ligne d’horizon", "route", "ville"], bonneReponse: 0 },
{ question: "lush vegetation", choix: ["végétation luxuriante", "désert", "forêt sèche"], bonneReponse: 0 },
{ question: "waterfall", choix: ["cascade", "rivière", "lac"], bonneReponse: 0 },
{ question: "the outskirts", choix: ["la périphérie", "centre-ville", "campagne"], bonneReponse: 0 }

];
